import { StyleSheet } from 'react-native';
import { colors, spacing, borderRadius } from '@/theme';
import { SONARR_BLUE } from './constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: spacing[4],
    paddingBottom: spacing[8],
  },
  welcomeSection: {
    alignItems: 'center',
    paddingVertical: spacing[6],
    marginBottom: spacing[4],
  },
  welcomeIcon: {
    width: 80,
    height: 80,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing[4],
  },
  welcomeTitle: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '700',
    marginBottom: spacing[2],
  },
  welcomeSubtitle: {
    color: colors.text.tertiary,
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
    paddingHorizontal: spacing[4],
  },
  connectionCard: {
    backgroundColor: colors.surface.default,
    borderRadius: borderRadius.xl,
    padding: spacing[4],
    marginBottom: spacing[4],
    overflow: 'hidden',
  },
  connectionGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 80,
  },
  connectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing[3],
  },
  statusIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing[3],
  },
  connectionInfo: {
    flex: 1,
  },
  connectionTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  connectionVersion: {
    color: colors.text.tertiary,
    fontSize: 13,
    marginTop: 2,
  },
  refreshButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surface.elevated,
    alignItems: 'center',
    justifyContent: 'center',
  },
  serverUrlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface.elevated,
    borderRadius: borderRadius.lg,
    padding: spacing[3],
    gap: spacing[2],
  },
  serverUrl: {
    color: colors.text.secondary,
    fontSize: 13,
    flex: 1,
    fontFamily: 'monospace',
  },
  section: {
    marginBottom: spacing[4],
  },
  sectionTitle: {
    color: colors.text.tertiary,
    fontSize: 13,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: spacing[3],
    marginLeft: spacing[1],
  },
  quickActionWrapper: {
    marginBottom: spacing[2],
  },
  quickAction: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface.default,
    borderRadius: borderRadius.xl,
    padding: spacing[3],
  },
  quickActionIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing[3],
  },
  quickActionLabel: {
    flex: 1,
    color: '#fff',
    fontSize: 15,
    fontWeight: '500',
  },
  settingCard: {
    backgroundColor: colors.surface.default,
    borderRadius: borderRadius.xl,
    overflow: 'hidden',
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing[4],
  },
  settingInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: spacing[3],
  },
  settingTextContainer: {
    marginLeft: spacing[3],
  },
  settingTitle: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '500',
  },
  settingSubtitle: {
    color: colors.text.muted,
    fontSize: 12,
    marginTop: 2,
  },
  disconnectButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: `${colors.status.error}15`,
    borderRadius: borderRadius.xl,
    paddingVertical: spacing[4],
    gap: spacing[2],
    marginTop: spacing[4],
  },
  disconnectButtonText: {
    color: colors.status.error,
    fontSize: 15,
    fontWeight: '600',
  },
  label: {
    color: colors.text.secondary,
    fontSize: 13,
    fontWeight: '600',
    marginBottom: spacing[2],
    marginTop: spacing[4],
    marginLeft: spacing[1],
  },
  input: {
    backgroundColor: colors.surface.default,
    borderRadius: borderRadius.lg,
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[3],
    color: '#fff',
    fontSize: 15,
  },
  urlRow: {
    flexDirection: 'row',
    gap: spacing[2],
    alignItems: 'stretch',
  },
  protocolPicker: {
    flexDirection: 'column',
    backgroundColor: colors.surface.default,
    borderRadius: borderRadius.lg,
    overflow: 'hidden',
  },
  protocolOption: {
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    alignItems: 'center',
  },
  protocolOptionActive: {
    backgroundColor: SONARR_BLUE,
  },
  protocolOptionText: {
    color: colors.text.muted,
    fontSize: 12,
    fontWeight: '600',
  },
  protocolOptionTextActive: {
    color: '#fff',
  },
  hostInput: {
    flex: 1,
  },
  portInput: {
    width: 72,
    textAlign: 'center',
  },
  apiKeyContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface.default,
    borderRadius: borderRadius.lg,
    paddingHorizontal: spacing[4],
  },
  apiKeyIcon: {
    marginRight: spacing[2],
  },
  apiKeyInput: {
    flex: 1,
    paddingVertical: spacing[3],
    color: '#fff',
    fontSize: 15,
  },
  hintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: spacing[2],
    gap: spacing[2],
    paddingLeft: spacing[1],
  },
  hint: {
    color: colors.text.muted,
    fontSize: 12,
    flex: 1,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: spacing[3],
    marginTop: spacing[6],
  },
  testUrlButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing[5],
    paddingVertical: spacing[4],
    borderRadius: borderRadius.xl,
    borderWidth: 2,
    gap: spacing[2],
  },
  testUrlButtonText: {
    fontSize: 15,
    fontWeight: '600',
  },
  connectButton: {
    flex: 1,
    borderRadius: borderRadius.xl,
    overflow: 'hidden',
  },
  connectGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing[4],
    gap: spacing[2],
  },
  connectButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
});
