export {
  jellyfinClient,
  getImageUrl,
  getStreamUrl,
  getAudioStreamUrl,
  getBookDownloadUrl,
  getSubtitleUrl,
  getTrickplayTileUrl,
} from './client';
export type { TrickplayInfo, TrickplayData } from './client';

export {
  getServerInfo,
  getServerPublicInfo,
  getPublicUsers,
  authenticateByName,
  logout,
  initiateQuickConnect,
  checkQuickConnectStatus,
  authenticateWithQuickConnect,
  authorizeQuickConnect,
  isQuickConnectEnabled,
  getCurrentUser,
  validateServerUrl,
} from './auth';
export type { ServerInfo, ServerPublicInfo } from './auth';

export {
  getLibraries,
  getItems,
  getItem,
  getCollectionItems,
  getResumeItems,
  getLatestMedia,
  getNextUp,
  getSimilarItems,
  getSuggestions,
  getFavorites,
  getFavoriteSongs,
  getSeasons,
  getEpisodes,
  getAlbumTracks,
  getArtistAlbums,
  getArtists,
  search,
  markAsFavorite,
  markAsPlayed,
  getGenres,
  createPlaylist,
  addToPlaylist,
  removeFromPlaylist,
  getPlaylists,
  getPlaylistItems,
  getLibraryConfig,
  getLibraryIcon,
  getLibraryItemTypes,
  shouldUseSquareVariant,
  getPerson,
  getPersonItems,
  COLLECTION_TYPE_CONFIG,
  DEFAULT_LIBRARY_CONFIG,
  groupLibrariesByType,
  getLibrariesByType,
  getLibraryIdsByType,
  getLatestMediaFromMultipleLibraries,
  getItemsFromMultipleLibraries,
  getInstantMix,
  getRecentlyPlayed,
  getMostPlayed,
} from './library';
export type {
  LibraryQueryParams,
  LibraryConfig,
  Genre,
  CreatePlaylistResult,
  PersonDetails,
  GroupedLibraries,
  SearchMediaType,
  SearchOptions,
} from './library';

export {
  getPlaybackInfo,
  reportPlaybackStart,
  reportPlaybackProgress,
  reportPlaybackStopped,
  selectBestMediaSource,
  determinePlayMethod,
  generatePlaySessionId,
  getMediaSegments,
} from './playback';
export type {
  PlaybackStartInfo,
  MediaSegment,
  MediaSegmentsResponse,
} from './playback';

export {
  getSystemInfo,
  getSessions,
  getItemCounts,
  getActivityLog,
  refreshLibrary,
  restartServer,
  shutdownServer,
  stopSession,
  sendSessionMessage,
  broadcastMessage,
  sendPlayCommand,
  sendPauseCommand,
  sendStopCommand,
  sendSeekCommand,
  sendNextTrackCommand,
  sendPreviousTrackCommand,
  getScheduledTasks,
  runScheduledTask,
  stopScheduledTask,
  getLogFiles,
  getUsers,
  disableUser,
  enableUser,
  resetUserPassword,
  deleteUser,
  getUserById,
  getMediaFolders,
  updateUserPolicy,
  updateUserName,
  createUser,
} from './admin';
export type {
  SystemInfo,
  SessionInfo,
  NowPlayingItem,
  PlayState,
  TranscodingInfo,
  ItemCounts,
  ActivityLogEntry,
  ActivityLogResponse,
  ScheduledTask,
  LogFile,
  UserInfo,
  MediaFolder,
} from './admin';

export {
  getLiveTvInfo,
  getGuideInfo,
  getChannels,
  getChannel,
  getPrograms,
  getRecommendedPrograms,
  getProgram,
  getRecordings,
  getTimers,
  createTimer,
  deleteTimer,
  setChannelFavorite,
  getChannelImageUrl,
  getProgramImageUrl,
  getLiveStreamUrl,
  getLiveHlsStreamUrl,
  getLiveDirectStreamUrl,
  getLiveTvPlaybackInfo,
  getRecordingFolders,
  getSeriesTimers,
  createSeriesTimer,
  cancelSeriesTimer,
  deleteRecording,
} from './livetv';
export type { SeriesTimerInfo } from './livetv';

export {
  getAuthParams,
  buildVideoStreamParams,
  buildHlsStreamParams,
  buildTranscodeParams,
  buildAudioStreamParams,
  buildImageParams,
} from './urlParams';
export type {
  BaseStreamParams,
  VideoStreamParams,
  AudioStreamParams,
  HlsStreamParams,
} from './urlParams';

export {
  jellyseerrClient,
  sonarrService,
  radarrService,
} from './external';
export type {
  JellyseerrAuthMethod,
  SonarrSeries,
  SonarrQueueItem,
  SonarrQueueResponse,
  SonarrRootFolder,
  SonarrQualityProfile,
  SonarrLookupResult,
  SonarrAddSeriesOptions,
  SonarrEpisode,
  SonarrCalendarEpisode,
  SonarrRelease,
  RadarrMovie,
  RadarrQueueItem,
  RadarrQueueResponse,
  RadarrRootFolder,
  RadarrQualityProfile,
  RadarrLookupResult,
  RadarrAddMovieOptions,
  RadarrRelease,
  RadarrCalendarMovie,
} from './external';
